### PR TITLE
Added pistons for java 1.12.2

### PR DESCRIPTION
**Pull request by AzathothYS**
Added piston, piston_head and sticky_piston for java 1.12.2

The changes have been tested with all modified block states by importing and exporting with Amulet on a 1.12.2 world.

### CODE REVIEW

**Comment by gentlegiantJGC** [comment]
Were these files generated by hand or through the complier?

**Comment by AzathothYS** [comment]
I did that by hand. Should I use the compiler instead?

**Comment by gentlegiantJGC** [comment]
Yes they need to exist in the pre-compiled database so they don't get removed the next time the complier is run

**Comment by AzathothYS** [comment]
I see now that this project is a bit more complex that what I expected.
Just a few comments: 
 - the link in README.md to the compiler project is broken
 - the compiler project lacks some documentation about how to contribute
Have a nice day.

**Pull request closed without merging**
